---
- name: ---------------------- | KUBERNETES CLUSTER DEPLOYMENT | ---------------------------------
  hosts: all
  become: all
  pre_tasks:
  - name: Verifying if enough resources Present
    fail: msg="Please make sure you have atlest 2000 MB RAM and 2 Cores"
    when: ansible_processor_count < 2 or ansible_memtotal_mb < 2000
  - name: Pre-Requisite-1 |Switching off swap|
    shell: swapoff -a
    when: ansible_swaptotal_mb > 0
  - name: Pre-Requisite-2 |Gathering selinux status|
    shell: getenforce | grep -i Enforcing | wc -l
    register: se_status
  - name: Pre-Requisite-3 |Switching off selinux|
    shell: setenforce 0
    when: se_status.stdout == '1'

  roles:
  - deploy_kubernetes

  post_tasks:
  - name: Post-Requisite Configuring | weave | network
    shell: kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n') >> /tmp/weave_network.txt
    args: 
      creates: /tmp/weave_network.txt
    when: inventory_hostname in groups["cluster-master"]
 
